{% set name = "pytest-variables" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4719b07f0f6e5d07829b19284a99d9159543a2e0336311f7bc4ee3b1617f595d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<38]

requirements:
  host:
    - python
    - hatch-vcs >=0.3
    - hatchling >=1.13
    - pip
  run:
    - python
    - pytest >=7.0.0

# INTERNALERROR> SystemExit: hjson import error, please make sure that hjson is installed
{% set deselect_tests = " --deselect=tests/test_variables.py::test_invalid_format[hjson]" %}

test:
  source_files:
    - tests
  imports:
    - pytest_variables
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v {{ deselect_tests }} tests
  requires:
    - pip
    - pytest
    - pyyaml
    - toml

about:
  home: https://github.com/pytest-dev/pytest-variables
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: pytest plugin for providing variables to tests/fixtures
  dev_url: https://github.com/pytest-dev/pytest-variables
  doc_url: https://github.com/pytest-dev/pytest-variables

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
