travis:
  secure:
    BINSTAR_TOKEN: PwZ96+dM7gaLddtDcFpnqVX/9BBJ61xXoLv3dH4vzQhoth8Mni3wgxNbnl5jI6DWp+pp8Xe/iW8IgZbxpg3NU76cOOsjLtXb48jV8n8a45e2wMBYs5shBi9HufyA8J9GR7m0Ahi6ZbZstdhiddDMR5gRSXriyX8dvaaOr4rVlsr/de+d628wwsWCkTQieRAmOFA6LEUiF0LSfDJrawFwALVJyMd4WxFCmULucaQQPApJVKC29UWCGQ7sW4huX1gvFH734hdDeoMuL77yu/UYBknvZGlJMR+WKNwhL7vnIgXLMMgEjHaqfB91wsq4h31F0UlZDO7cdYUShjo00OGSRYDXZ8m5z3SgS7BaZou0M4SHJjQZxSlgj3xvqXV2EN6QI8M8/G36rFByq+QTNJScLq1HhGukJmS6jPIuwvIMEsmd268dQvrtWVCQafdyL6Dd5+bxrwP3/IjxvVVMjRXgnY5rONEnPj7uodxLdaR6qpkMy4/ThlNgnC6iN/3T7MVX9xh9pab4IhtmbBg2zMlOB8B7tFXbUYiGGjX4+o7Xa+pNiP0jQXNrLsQdxjUA1VywlCNxH7nzInRIpBott/T9Z6FrC4r092ocfVVAmjlbDsB2IP5Mcq5AWETD+A1/0sESY1V7fB3LV9InPSBrGuU3ZDCWfS2Zsi+ztB6OV7byZKM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
